# fly.toml app configuration file generated for reaktivities on 2023-10-02T14:24:37+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "reaktivities"
primary_region = "syd"

[build]
  image = "mirkokarac/reactivities:latest"

[env]
  ASPNETCORE_URLS = "http://+:8080"
  Cloudinary__ApiKey = "978566162393278"
  Cloudinary__CloudName = "dum5amo5y"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
